### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Just1Developer** [Mor-uto/SimpleStringEncrypter#1]
Hey, saw you [probably] deleted your Spigot account after presenting this, so I still wanted to message you.
Practice makes perfect, if you're into cyber security and all that it would be worth it to look into how to actually achieve what you want. It's absolutely normal to look foolish at the start, that's the only way you'll learn (btw, I made something exactly like that when I started getting into that too).

If you're still somewhat of a beginner and want to learn more, Harvard offers a [free online course](https://pll.harvard.edu/course/cs50-introduction-computer-science) on computer science which might be worth checking out.
Have a good one, and happy coding!

Also sorry I made an issue on Github to tell you this.

**Comment by Mor-uto** [comment]
> Hey, saw you [probably] deleted your Spigot account after presenting this, so I still wanted to message you. Practice makes perfect, if you're into cyber security and all that it would be worth it to look into how to actually achieve what you want. It's absolutely normal to look foolish at the start, that's the only way you'll learn (btw, I made something exactly like that when I started getting into that too).
> 
> If you're still somewhat of a beginner and want to learn more, Harvard offers a [free online course](https://pll.harvard.edu/course/cs50-introduction-computer-science) on computer science which might be worth checking out. Have a good one, and happy coding!
> 
> Also sorry I made an issue on Github to tell you this.

ty for telling me this, btw i didnt delete it i just privated it like uh from pirvacy settings becasuse i have 2 ppl stalking me on spigotmc & ill unprivate it soon
